export const CATEGORY_TYPE = {
    // SET_CATEGORY: 'SET_CATEGORY',
    SET_CATEGORY_START: 'SET_CATEGORY_START', 
    SET_CATEGORY_FAIL: 'SET_CATEGORY_FAIL',
    SET_CATEGORY_SUCCESS: 'SET_CATEGORY_SUCCESS', 
}